version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/taskbook-backend"
    schedule:
      interval: "quarterly"
    target-branch: main
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/taskbook-frontend"
    schedule:
      interval: "quarterly"
    target-branch: main
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@types/*"
          - "rxjs"
          - "tslib"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    target-branch: main
    open-pull-requests-limit: 10
