server:
  port: 26160
  error:
    path: /error

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/taskbook
    username: taskbook
    password: taskbook
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    date-format: tools.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE

taskbook:
  jwt:
    secret: "0000000000"
    lifetime: 864000

logging:
  level:
    io.github.malczuuu: debug
